// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (identical(defaultTargetPlatform, TargetPlatform.android)) {
      return android;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.iOS)) {
      return ios;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.macOS)) {
      return macos;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx6NEyMZJOhPTjt9lGav26BtE_q2h1-kc',
    appId: '1:101710107051:android:04892d75d50610af46c2ee',
    messagingSenderId: '101710107051',
    projectId: 'c-billing-4744a',
    storageBucket: 'c-billing-4744a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx6NEyMZJOhPTjt9lGav26BtE_q2h1-kc',
    appId: '1:101710107051:ios:04892d75d50610af46c2ee',
    messagingSenderId: '101710107051',
    projectId: 'c-billing-4744a',
    storageBucket: 'c-billing-4744a.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx6NEyMZJOhPTjt9lGav26BtE_q2h1-kc',
    appId: '1:101710107051:ios:04892d75d50610af46c2ee',
    messagingSenderId: '101710107051',
    projectId: 'c-billing-4744a',
    storageBucket: 'c-billing-4744a.firebasestorage.app',
    iosBundleId: 'com.example.cBilling',
  );
}
